Enhancement/date range validation
ss77995ss/baseball-stats-python pull request #10
Opened 2024-10-26 05:42 UTC by jeff3071

## Summary

Add date range validation for Statcast data function.

- Implement validate_date_range function to check date format (YYYY-MM-DD)
- Ensure end date is not earlier than start date
- Add unit tests to verify validation logic for date format and range

2024-10-26 18:31 UTC, ss77995ss requested changes
Nice work! Thanks for your contributions.
I have added some comments. Please have a look.

2024-10-26 18:31 UTC, ss77995ss commented on .gitignore
> +venv/
This is my mistake. In [CONTRIBUTING.md](https://github.com/ss77995ss/baseball-stats-python/blob/main/CONTRIBUTING.md) `venv` should be `.venv`

```diff
- python -m venv venv
+ python -m venv .venv
```

2024-10-26 18:31 UTC, ss77995ss commented on src/baseball_stats_python/statcast/minor_statcast_search.py
> +    if start_dt or end_dt:
Only need one validation since `statcast_batter_search` and `statcast_pitcher_search` also call `statcast_search`

2024-10-26 18:31 UTC, ss77995ss commented on src/baseball_stats_python/statcast/statcast_search.py
> +    if start_dt or end_dt:
Same as comment in `statcast_search.py`

2024-10-26 18:31 UTC, ss77995ss commented on src/baseball_stats_python/utils/utils.py
> +    try:
I would prefer `try-except` format first then check range
For example:
```python
try:
    start_date = datetime.strptime(start_dt, date_format)
    end_date = datetime.strptime(end_dt, date_format)
except ValueError as e:
    raise ValueError(e)

if end_date < start_date:
    raise ValueError("end_dt cannot be earlier than start_dt.")
```

Thus, we can know the error is from date format or date range.

2024-10-26 18:31 UTC, ss77995ss commented on src/baseball_stats_python/utils/utils.py
> +    try:
Also `start_dt` and `end_dt` are allowed to have one empty string `""` between them.

Ex: `{"start_dt": "", "end_dt": "2024-10-27"}` or `{"start_dt": "2024-10-01", "end_dt": ""}`

We might also want to handle these situations

2024-10-27 06:40 UTC, jeff3071 commented
Here is update note:

- removed validation in `statcast_batter_search` and `statcast_pitcher_search`. 
- support empty string input for `validate_date_range`.
- add more test cases to confirm it works as expected.

2024-10-27 14:36 UTC, ss77995ss approved these changes
LGTM! Thank you for your contributions! I'll merge this PR ASAP.

2024-10-27 14:36 UTC, ss77995ss commented on CONTRIBUTING.md
> +python -m venv .venv
Thanks 🙏

2024-10-27 15:37 UTC, merged